# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        name: osCsid

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        base_urls: '%env(ASSETS_BASE_URLS)%'
        version: '%env(ASSETS_VERSION)%'
        packages:
            images: 
                base_urls: '%env(ASSETS_BASE_URLS)%/images'
            pander:
                base_urls: '%env(ASSETS_BASE_URLS)%/pub/src/pander'
            glassofvenice: 
                base_urls: '%env(ASSETS_BASE_URLS)%/pub/src/glassofvenice'
            build:
                base_urls: '%env(ASSETS_BASE_URLS)%/pub/build'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
